# Basic
name:               "prtmsh"

author:
  #facebook:         your-id
  #youtubeUser:      your-id
  #youtubeChannel:   your-id
  twitter:          prthmshs
  github:           pratos
  #stackoverflow:    your-id
  #quora:            your-id
  linkedin:         prathamesh-sarang-392b9219
  #pinterest:        your-id
  #googlePlus:       your-id
  #instagram:        your-id
  #reddit:           your-id
  medium:           prato_s
  #tumblr:           your-id
  email:            pratham.sarang9@gmail.com

copyright:
  year:             2017
  name:             Prathamesh

# Google-analytics
google-analytics:
  id:               "UA-90835968-1"

# Disqus
disqus:
  id:               "thoth-1"

# URL
url:                "https://pratos.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Kolkata
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Activities"
    url:            "/activities"
  - name:           "Archive"
    url:            "/writing"
  - name:           "Bookmarks"
    url:            "/reading"
  - name:           "Comics"
    url:            "/comics"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
